-- Categories table
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique
);

-- Products table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  price numeric(12,2) not null,
  description text,
  image_url text,
  stock integer not null default 0,
  created_at timestamptz not null default now()
);

-- User profile table, linked to auth.users
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

-- Migration for existing databases that created users without email.
alter table public.users add column if not exists email text;

-- Backfill profile emails from Supabase Auth users.
update public.users u
set email = a.email
from auth.users a
where u.id = a.id
  and (u.email is null or btrim(u.email) = '');

do $$
begin
  if exists (
    select 1 from public.users
    where email is null or btrim(email) = ''
  ) then
    raise notice 'Some public.users rows still have no email. Fill them manually before enforcing NOT NULL.';
  else
    alter table public.users alter column email set not null;
  end if;
end $$;

-- Enforce case-insensitive uniqueness for emails.
create unique index if not exists users_email_unique_idx on public.users (lower(email));

-- Optional indexes
create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_products_created_at on public.products(created_at desc);

-- Global product display settings. The singleton id keeps this setting scoped to the site.
create table if not exists public.product_settings (
  id integer primary key check (id = 1),
  is_price_disabled boolean not null default false
);

insert into public.product_settings (id, is_price_disabled)
values (1, false)
on conflict (id) do nothing;
